export const orders = [
    {
        date: "20 May 2021",
        productID: '0001',
        orderID: '676FGF',
        quantity: 8,
        address:'#15 Austin St. Greenview Village Pamplona 3, LPC, 1740',
        status: '-',
    },
    {
        date: "20 May 2021",
        productID: '0002',
        orderID: '8787GUA',
        quantity: 5,
        address:'#15 Austin St. Greenview Village Pamplona 3, LPC, 1740',
        status: 'Received',
    },
    {
        date: "20 May 2021",
        productID: '0003',
        orderID: '2498YDS',
        quantity: 7,
        address:'#15 Austin St. Greenview Village Pamplona 3, LPC, 1740',
        status: '-',
    },
    {
        date: "20 May 2021",
        productID: '0004',
        orderID: '2839YSB',
        quantity: 2,
        address:'#15 Austin St. Greenview Village Pamplona 3, LPC, 1740',
        status: 'To Ship',
    },
    {
        date: "20 May 2021",
        productID: '0005',
        orderID: '9243DON',
        quantity: 6,
        address:'#15 Austin St. Greenview Village Pamplona 3, LPC, 1740',
        status: 'Received',
    },
    {
        date: "20 May 2021",
        productID: '0006',
        orderID: '9243DON',
        quantity: 6,
        address:'#15 Austin St. Greenview Village Pamplona 3, LPC, 1740',
        status: 'Received',
    },
    {
        date: "20 May 2021",
        productID: '0007',
        orderID: '9243DON',
        quantity: 6,
        address:'#15 Austin St. Greenview Village Pamplona 3, LPC, 1740',
        status: 'Received',
    },
]

export const products = [
    {
        name: 'EL HJEFE and Switching Lanes Stickers',
        id: '5uii2KXQUoeFrjYZWufQ',
        category: 'stickers',
        color: ['black'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FEL-HJEFE-and-Switching-Lanes-Stickers.png?alt=media&token=4c4a0a79-8734-463d-a042-c10026ec677d',
        price: 1.5,
        size: [],
        style: [],
        sales: 7,
        status: 'available',
    },
    {
        name: 'Beatsby Lonza Hoodie',
        id: '95uTx3GYtXdtdZATzJMb',
        category: 'hoodie',
        color: ['white'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FBeatsby%20Lonza%20Hoodie.png?alt=media&token=c98b54ff-1c14-4bdd-bc2c-88255a629615',
        price: 28,
        size: ["S", "M", "L", "XL"],
        style: [],
        sales: 13,
        status: 'not available',
    },
    {
        name: 'EL HJEFE Mask',
        id: 'His78NSKOw16cWkRNWr6',
        category: 'mask',
        color: ['black'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FEL-HJEFE-Mask.png?alt=media&token=7df532e2-369d-424c-b5d4-eae09510e201',
        price: 8,
        size: [],
        style: [],
        sales: 12,
        status: 'available',
    },
    {
        name: 'EL HJEFE Socks',
        id: 'QozVaUWujZCMmLGWOJ1j',
        category: 'socks',
        color: ['black', 'white', 'black & white', 'black & red', 'black & gray'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FEl%20Hjefe%20Socks.jpg?alt=media&token=ca452c44-f9ef-462a-883b-45f84cf84ddb',
        price: 12,
        size: [9, 10, 11, 12],
        style: [],
        sales: 9,
        status: 'available',
    },
    {
        name: 'EL HJEFE Boss Cigar Box',
        id: 'VGfxS0ZSurj44ZKWONbp',
        category: 'cigar box',
        color: [],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FEL-HJEFE-Boss-Cigar-Box.png?alt=media&token=671ee72a-dfc8-44de-98fb-ab57771febfe',
        price: 25,
        size: [],
        style: [],
        sales: 2,
        status: 'available',
    },
    {
        name: 'EL HJEFE Black Tee',
        id: 'Y16cGnIasbFuLfzWpPES',
        category: 't-shirt',
        color: ['black'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FEL-HJEFE-Black-Tee.png?alt=media&token=05bcf71b-6936-4e39-9776-977d7ac51163',
        price: 25,
        size: [],
        style: [],
        sales: 6,
        status: 'available',
    },
    {
        name: 'Switching Lanes Snapback (Cap)',
        id: 'a7hAhlXVevBcI5gXElHM',
        category: 'cap',
        color: ['black'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FSwitching-Lanes-Snapback.png?alt=media&token=a585fd96-ce22-4930-9ef7-62052f60314c',
        price: 25,
        size: [],
        style: [],
        sales: 7,
        status: 'not available',
    },
    // {
    //     name: 'EL HJEFE Slides',
    //     id: 'bwqoyJPDOOAmG9qwkRcQ',
    //     category: 'slides',
    //     color: ['vlack'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FEL%20HJEFE%20SLIDES.png?alt=media&token=97df009c-41ec-41f1-814d-8d45af27e65b',
    //     price: 25,
    //     size: [9, 10, 11, 12],
    //     style: [],
    //     sales: 10,
    //     status: 'not available',
    // },
    // {
    //     name: 'Switching Lanes T-Shirt',
    //     id: 'c4DMwwqLGema4GrGZHGt',
    //     category: 't-shirt',
    //     color: ['black'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FSwitching-Lanes-Tshirt.png?alt=media&token=5edb4957-3acd-4c28-a4ec-992f473a1bd8',
    //     price: 30,
    //     size: [],
    //     style: [],
    //     sales: 5,
    //     status: 'not available',
    // },
    // {
    //     name: 'EL HJEFE Mixtape T-Shirt',
    //     id: 'qq4ipnz0wnNPoISs22nr',
    //     category: 't-shirt',
    //     color: ['black'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     picture: 'https://firebasestorage.googleapis.com/v0/b/lonza-da8e4.appspot.com/o/pictures%2FEL-HJEFE-Mixtape-Tshirt.png?alt=media&token=c3ca1b89-887b-4498-a1a6-1b38a59fae63',
    //     price: 30,
    //     size: [],
    //     style: [],
    //     sales: 1,
    //     status: 'available',
    // },
]